### ISSUE TITLE
Token disappears on hover

### ISSUE THREAD

**Issue by AJAnderson** [Zzarek/FoundryHotSeatObserver#11]
Running VTT 0.6.0 and hotseat observer 0.5.5.02.

When looking at tokens in a player view hosted on a localhost window. When hovering over the token, the picture disappears and does not reappear until the scene is reloaded.

Tracked down to Hotseat by progressively disabling modules until I disabled Hotseat and found it.

DnD 5e 0.91 system

**Comment by Zzarek** [comment]
@AJAnderson 

Could you share your settings with me, if any were not default?

**Comment by AJAnderson** [comment]
A quick thing I noticed when I booted the player view in a private browser window the first time was the error "Observer dynamiceffects.noGM" or something like that.

My settings are:
Enable Hot Seat Module: True
Toggle GM Select Mode: False
Hot Seat Player Name: Observer
Camera Tracks Initiative: False
Hide Hot Seat Icons: True

**Comment by Zzarek** [comment]
@AJAnderson 

OK Im back. 

So the issue / request for Hide Hot Seat Icons was the idea a guy wanted to have invisible icons by still active tokens in initiative. The use case is that he was controlling the table, and his players are moving figures around on a horizontal tv. They dont have circular bases, so the icon under them was jarring. 

Turn off Hide Hot Seat Icons.

If you want I can find a way to explain that feature better in its description.

**Comment by Zzarek** [comment]
This worked for another user.
