### ISSUE TITLE
Map Panning When Stepping Through Combat Tracker

### ISSUE THREAD

**Issue by mr-barakas** [Zzarek/FoundryHotSeatObserver#5]
I have a new request for another toggle, this time controlling whether the "camera" pans to the current token who's turn it is in the combat tracker.  I'm playing with figurines sitting on the TV on top of their digital token so I need the map to stay static unless I'm the one moving the map around.

Issue Replication: Initiate a combat by adding players and NPCs to the combat tracker.  Begin Combat and then click through the Turns.  Whenever a player token is the next token in the combat order the camera will pan to that token.  The action of this panning de-syncs the digital tokens from the real figurines sitting on the TV.

Note1: It does not pan when the token is an NPC, just a player token.

The request is for a toggle that will stop the panning of the map on the Player Screen (i.e., TV) during combat encounters.

**Comment by GMToolbox** [comment]
I was actually going to request the same here. Upvotting

**Comment by GMToolbox** [comment]
Haven't see you around zzarek. Are you abandoning this project? The pan feature being turned off would really help out a lot.

**Comment by Zzarek** [comment]
@erogroth 

Ill give a status update. Im upgrading my computer at this time, and Intend to get my dev tools and situation cleaned up next weekend. I apologize it is moving as slow as it is.

**Comment by GMToolbox** [comment]
Thanks for the update. I hadn't seen you in discord so wasn't sure if you were still around.

**Comment by Zzarek** [comment]
@mr-barakas & @erogroth 

Good news bad news. 

Good news, the fix is easy, I just have to implement it, I got it working last night.on my new computer since my laptop was dragging so much i hadnt wanted to work on it.

Bad news.  That was 9pm. As of this morning my My new MOBO is on the way back to the factory,

**Comment by Zzarek** [comment]
@mr-barakas @erogroth 

What a series of events, you guys don't even want to know them all.

My Sincerest apologies it took so long. If you like you can test branch v05. I added a setting that should enable this.

https://raw.githubusercontent.com/zzarek/FoundryHotSeatObserver/v05/module.json

**Comment by mr-barakas** [comment]
Thanks Zzarek.  The v05 branch has resolved the panning issue!

**Comment by mr-barakas** [comment]
Closing the issue.  Thanks again Zzarek.
