### ISSUE TITLE
Sight while token is hidden

### ISSUE THREAD

**Issue by GMToolbox** [Zzarek/FoundryHotSeatObserver#6]
As we discussed in discord, I would like the ability to still see the active token's vision even if the token is hidden.

**Comment by Zzarek** [comment]
@erogroth - Im starting in on estimating this one.

**Comment by GMToolbox** [comment]
Nice. Looking forward to it.

**Comment by Zzarek** [comment]
@erogroth  I have it working in a branch, but i dont like the way it works. I would appreciate you taking it out for a spin though.

**Comment by GMToolbox** [comment]
I'll take a look. Is it not part of the current release?

**Comment by GMToolbox** [comment]
I found it. Looks good to me. I have all the tokens hidden and sight is working. I will have to do some more testing with the players logged in and make sure they can see but so far so good.

**Comment by PersistentProgrammer** [comment]
@erogroth - its on a branch, actually. (HiddenTokens)

Yesterday, i started trying to improve it, and the functionality on that branch isnt operable. The problem im having (after about a day of fiddling) is that i need to modify token.icon, and i'm finding inconsistencies on when that is an option.

What i had it doing is going invisible during combat, and the experience was a bit poor.  

Would you be available to test next weekend?

**Comment by PersistentProgrammer** [comment]
Im actually surprised it is working...
